# Generated by Django 4.2.9 on 2024-02-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='health_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
