# Generated by Django 4.2.9 on 2024-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_medicalrecord_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='childprofile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
