# Generated by Django 4.2.9 on 2024-02-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_childprofile_picture_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apis.profile'),
        ),
    ]
